"""git_api URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from django.http import JsonResponse


d= {
  "total_count": 3,
  "incomplete_results": False,
  "items": [
    {
      "id": 73686474,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MzY4NjQ3NA==",
      "name": "squealy",
      "full_name": "hashedin/squealy",
      "owner": {
        "login": "hashedin",
        "id": 1456904,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0NTY5MDQ=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/1456904?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hashedin",
        "html_url": "https://github.com/hashedin",
        "followers_url": "https://api.github.com/users/hashedin/followers",
        "following_url": "https://api.github.com/users/hashedin/following{/other_user}",
        "gists_url": "https://api.github.com/users/hashedin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/hashedin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/hashedin/subscriptions",
        "organizations_url": "https://api.github.com/users/hashedin/orgs",
        "repos_url": "https://api.github.com/users/hashedin/repos",
        "events_url": "https://api.github.com/users/hashedin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/hashedin/received_events",
        "type": "Organization",
        "site_admin": False
      },
      "private": False,
      "html_url": "https://github.com/hashedin/squealy",
      "description": "Develop APIs for Charts and Dashboards by writing SQL Queries",
      "fork": False,
      "url": "https://api.github.com/repos/hashedin/squealy",
      "forks_url": "https://api.github.com/repos/hashedin/squealy/forks",
      "keys_url": "https://api.github.com/repos/hashedin/squealy/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/hashedin/squealy/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/hashedin/squealy/teams",
      "hooks_url": "https://api.github.com/repos/hashedin/squealy/hooks",
      "issue_events_url": "https://api.github.com/repos/hashedin/squealy/issues/events{/number}",
      "events_url": "https://api.github.com/repos/hashedin/squealy/events",
      "assignees_url": "https://api.github.com/repos/hashedin/squealy/assignees{/user}",
      "branches_url": "https://api.github.com/repos/hashedin/squealy/branches{/branch}",
      "tags_url": "https://api.github.com/repos/hashedin/squealy/tags",
      "blobs_url": "https://api.github.com/repos/hashedin/squealy/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/hashedin/squealy/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/hashedin/squealy/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/hashedin/squealy/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/hashedin/squealy/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/hashedin/squealy/languages",
      "stargazers_url": "https://api.github.com/repos/hashedin/squealy/stargazers",
      "contributors_url": "https://api.github.com/repos/hashedin/squealy/contributors",
      "subscribers_url": "https://api.github.com/repos/hashedin/squealy/subscribers",
      "subscription_url": "https://api.github.com/repos/hashedin/squealy/subscription",
      "commits_url": "https://api.github.com/repos/hashedin/squealy/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/hashedin/squealy/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/hashedin/squealy/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/hashedin/squealy/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/hashedin/squealy/contents/{+path}",
      "compare_url": "https://api.github.com/repos/hashedin/squealy/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/hashedin/squealy/merges",
      "archive_url": "https://api.github.com/repos/hashedin/squealy/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/hashedin/squealy/downloads",
      "issues_url": "https://api.github.com/repos/hashedin/squealy/issues{/number}",
      "pulls_url": "https://api.github.com/repos/hashedin/squealy/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/hashedin/squealy/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/hashedin/squealy/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/hashedin/squealy/labels{/name}",
      "releases_url": "https://api.github.com/repos/hashedin/squealy/releases{/id}",
      "deployments_url": "https://api.github.com/repos/hashedin/squealy/deployments",
      "created_at": "2016-11-14T09:06:30Z",
      "updated_at": "2018-08-02T18:03:59Z",
      "pushed_at": "2018-07-31T13:25:32Z",
      "git_url": "git://github.com/hashedin/squealy.git",
      "ssh_url": "git@github.com:hashedin/squealy.git",
      "clone_url": "https://github.com/hashedin/squealy.git",
      "svn_url": "https://github.com/hashedin/squealy",
      "homepage": "https://hashedin.com/2017/04/24/squealy-intro-how-to-build-customized-dashboard/",
      "size": 40266,
      "stargazers_count": 542,
      "watchers_count": 542,
      "language": "JavaScript",
      "has_issues": True,
      "has_projects": True,
      "has_downloads": True,
      "has_wiki": True,
      "has_pages": False,
      "forks_count": 42,
      "mirror_url": None,
      "archived": False,
      "open_issues_count": 9,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "forks": 42,
      "open_issues": 9,
      "watchers": 542,
      "default_branch": "phase-2",
      "score": 134.29703
    },
    {
      "id": 142426627,
      "node_id": "MDEwOlJlcG9zaXRvcnkxNDI0MjY2Mjc=",
      "name": "squealy-ui",
      "full_name": "nikitha444/squealy-ui",
      "owner": {
        "login": "nikitha444",
        "id": 36027603,
        "node_id": "MDQ6VXNlcjM2MDI3NjAz",
        "avatar_url": "https://avatars2.githubusercontent.com/u/36027603?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/nikitha444",
        "html_url": "https://github.com/nikitha444",
        "followers_url": "https://api.github.com/users/nikitha444/followers",
        "following_url": "https://api.github.com/users/nikitha444/following{/other_user}",
        "gists_url": "https://api.github.com/users/nikitha444/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/nikitha444/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/nikitha444/subscriptions",
        "organizations_url": "https://api.github.com/users/nikitha444/orgs",
        "repos_url": "https://api.github.com/users/nikitha444/repos",
        "events_url": "https://api.github.com/users/nikitha444/events{/privacy}",
        "received_events_url": "https://api.github.com/users/nikitha444/received_events",
        "type": "User",
        "site_admin": False
      },
      "private": False,
      "html_url": "https://github.com/nikitha444/squealy-ui",
      "description": None,
      "fork": False,
      "url": "https://api.github.com/repos/nikitha444/squealy-ui",
      "forks_url": "https://api.github.com/repos/nikitha444/squealy-ui/forks",
      "keys_url": "https://api.github.com/repos/nikitha444/squealy-ui/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/nikitha444/squealy-ui/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/nikitha444/squealy-ui/teams",
      "hooks_url": "https://api.github.com/repos/nikitha444/squealy-ui/hooks",
      "issue_events_url": "https://api.github.com/repos/nikitha444/squealy-ui/issues/events{/number}",
      "events_url": "https://api.github.com/repos/nikitha444/squealy-ui/events",
      "assignees_url": "https://api.github.com/repos/nikitha444/squealy-ui/assignees{/user}",
      "branches_url": "https://api.github.com/repos/nikitha444/squealy-ui/branches{/branch}",
      "tags_url": "https://api.github.com/repos/nikitha444/squealy-ui/tags",
      "blobs_url": "https://api.github.com/repos/nikitha444/squealy-ui/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/nikitha444/squealy-ui/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/nikitha444/squealy-ui/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/nikitha444/squealy-ui/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/nikitha444/squealy-ui/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/nikitha444/squealy-ui/languages",
      "stargazers_url": "https://api.github.com/repos/nikitha444/squealy-ui/stargazers",
      "contributors_url": "https://api.github.com/repos/nikitha444/squealy-ui/contributors",
      "subscribers_url": "https://api.github.com/repos/nikitha444/squealy-ui/subscribers",
      "subscription_url": "https://api.github.com/repos/nikitha444/squealy-ui/subscription",
      "commits_url": "https://api.github.com/repos/nikitha444/squealy-ui/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/nikitha444/squealy-ui/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/nikitha444/squealy-ui/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/nikitha444/squealy-ui/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/nikitha444/squealy-ui/contents/{+path}",
      "compare_url": "https://api.github.com/repos/nikitha444/squealy-ui/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/nikitha444/squealy-ui/merges",
      "archive_url": "https://api.github.com/repos/nikitha444/squealy-ui/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/nikitha444/squealy-ui/downloads",
      "issues_url": "https://api.github.com/repos/nikitha444/squealy-ui/issues{/number}",
      "pulls_url": "https://api.github.com/repos/nikitha444/squealy-ui/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/nikitha444/squealy-ui/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/nikitha444/squealy-ui/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/nikitha444/squealy-ui/labels{/name}",
      "releases_url": "https://api.github.com/repos/nikitha444/squealy-ui/releases{/id}",
      "deployments_url": "https://api.github.com/repos/nikitha444/squealy-ui/deployments",
      "created_at": "2018-07-26T10:36:05Z",
      "updated_at": "2018-07-26T10:38:15Z",
      "pushed_at": "2018-07-26T10:38:14Z",
      "git_url": "git://github.com/nikitha444/squealy-ui.git",
      "ssh_url": "git@github.com:nikitha444/squealy-ui.git",
      "clone_url": "https://github.com/nikitha444/squealy-ui.git",
      "svn_url": "https://github.com/nikitha444/squealy-ui",
      "homepage": None,
      "size": 61,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "JavaScript",
      "has_issues": True,
      "has_projects": True,
      "has_downloads": True,
      "has_wiki": True,
      "has_pages": False,
      "forks_count": 0,
      "mirror_url": None,
      "archived": False,
      "open_issues_count": 0,
      "license": None,
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "master",
      "score": 17.943787
    },
    {
      "id": 79814333,
      "node_id": "MDEwOlJlcG9zaXRvcnk3OTgxNDMzMw==",
      "name": "test-squealy",
      "full_name": "devashishsharma2302/test-squealy",
      "owner": {
        "login": "devashishsharma2302",
        "id": 16999995,
        "node_id": "MDQ6VXNlcjE2OTk5OTk1",
        "avatar_url": "https://avatars1.githubusercontent.com/u/16999995?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/devashishsharma2302",
        "html_url": "https://github.com/devashishsharma2302",
        "followers_url": "https://api.github.com/users/devashishsharma2302/followers",
        "following_url": "https://api.github.com/users/devashishsharma2302/following{/other_user}",
        "gists_url": "https://api.github.com/users/devashishsharma2302/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/devashishsharma2302/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/devashishsharma2302/subscriptions",
        "organizations_url": "https://api.github.com/users/devashishsharma2302/orgs",
        "repos_url": "https://api.github.com/users/devashishsharma2302/repos",
        "events_url": "https://api.github.com/users/devashishsharma2302/events{/privacy}",
        "received_events_url": "https://api.github.com/users/devashishsharma2302/received_events",
        "type": "User",
        "site_admin": False
      },
      "private": False,
      "html_url": "https://github.com/devashishsharma2302/test-squealy",
      "description": None,
      "fork": False,
      "url": "https://api.github.com/repos/devashishsharma2302/test-squealy",
      "forks_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/forks",
      "keys_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/teams",
      "hooks_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/hooks",
      "issue_events_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/issues/events{/number}",
      "events_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/events",
      "assignees_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/assignees{/user}",
      "branches_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/branches{/branch}",
      "tags_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/tags",
      "blobs_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/languages",
      "stargazers_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/stargazers",
      "contributors_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/contributors",
      "subscribers_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/subscribers",
      "subscription_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/subscription",
      "commits_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/contents/{+path}",
      "compare_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/merges",
      "archive_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/downloads",
      "issues_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/issues{/number}",
      "pulls_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/labels{/name}",
      "releases_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/releases{/id}",
      "deployments_url": "https://api.github.com/repos/devashishsharma2302/test-squealy/deployments",
      "created_at": "2017-01-23T14:57:04Z",
      "updated_at": "2017-01-23T15:09:29Z",
      "pushed_at": "2017-01-24T07:23:57Z",
      "git_url": "git://github.com/devashishsharma2302/test-squealy.git",
      "ssh_url": "git@github.com:devashishsharma2302/test-squealy.git",
      "clone_url": "https://github.com/devashishsharma2302/test-squealy.git",
      "svn_url": "https://github.com/devashishsharma2302/test-squealy",
      "homepage": None,
      "size": 21,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "Python",
      "has_issues": True,
      "has_projects": True,
      "has_downloads": True,
      "has_wiki": True,
      "has_pages": False,
      "forks_count": 0,
      "mirror_url": None,
      "archived": False,
      "open_issues_count": 0,
      "license": None,
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "master",
      "score": 17.545763
    }
  ]
}

def get_api(request):
    return JsonResponse(d)


urlpatterns = [
    url(r'^core/', get_api),
]